(function(){
if(!document.getElementById('section-media'))return;
const categories=['Romantic','Elegant','Warm','Nusantara','Modern'];
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
let music=[],defaultSets=[],activeDefaultId='';
function mediaNotice(title,message,danger=false){const m=document.getElementById('adminActionModal');if(!m)return;document.getElementById('adminActionKicker').textContent=danger?'TERJADI KESALAHAN':'MEDIA MANAGER';document.getElementById('adminActionTitle').textContent=title;document.getElementById('adminActionMessage').textContent=message;document.getElementById('adminActionField').classList.add('hidden');document.getElementById('adminDialogConfirm').textContent='Oke';document.querySelector('[data-dialog-cancel]')?.classList.add('hidden');m.classList.add('show');m.setAttribute('aria-hidden','false');document.getElementById('adminDialogConfirm').onclick=()=>{m.classList.remove('show');m.setAttribute('aria-hidden','true')}}
function mediaConfirm(title,message,callback){const m=document.getElementById('adminActionModal');if(!m)return;document.getElementById('adminActionKicker').textContent='MEDIA MANAGER';document.getElementById('adminActionTitle').textContent=title;document.getElementById('adminActionMessage').textContent=message;document.getElementById('adminActionField').classList.add('hidden');const c=document.querySelector('[data-dialog-cancel]');c?.classList.remove('hidden');document.getElementById('adminDialogConfirm').textContent='Lanjutkan';m.classList.add('show');m.setAttribute('aria-hidden','false');document.getElementById('adminDialogConfirm').onclick=async()=>{m.classList.remove('show');m.setAttribute('aria-hidden','true');await callback()}}
async function uploadAdminFile(file,path){const {error}=await supabaseClient.storage.from('bernaung-media').upload(path,file,{cacheControl:'3600',upsert:true,contentType:file.type});if(error)throw error;return supabaseClient.storage.from('bernaung-media').getPublicUrl(path).data.publicUrl}
async function loadMusic(){if(!supabaseReady())return;const {data,error}=await supabaseClient.from('music_library').select('*').order('category').order('title');if(error){mediaNotice('Gagal memuat MP3',error.message,true);return}music=data||[];renderMusic()}
function renderMusic(){const box=document.getElementById('musicManagerList');if(!box)return;if(!music.length){box.innerHTML='<div class="media-empty"><div class="media-empty-icon">♪</div><strong>Belum ada musik</strong><p>Tambahkan musik MP3 agar customer dapat memilih lagu untuk undangan mereka.</p><button type="button" class="text-btn media-empty-action" data-add-empty-music>+ Tambah MP3</button></div>';return}box.innerHTML=music.map(m=>`<article class="media-item"><div class="media-item-main"><span class="mini-label">${esc(m.category)}${m.active?'':' · NONAKTIF'}</span><strong>${esc(m.title)}</strong><small>${esc(m.file_url)}</small><audio controls preload="none" src="${esc(m.file_url)}"></audio></div><div class="row-actions"><button type="button" class="text-btn" data-edit-music="${esc(m.id)}">Edit</button><button type="button" class="text-btn danger-text" data-delete-music="${esc(m.id)}">Hapus</button></div></article>`).join('')}
function musicModal(item=null){const m=document.getElementById('adminMediaModal');m.classList.remove('hidden');m.querySelector('#mediaMusicTitle').textContent=item?'Edit MP3':'Tambah MP3';m.querySelector('#mediaMusicForm').dataset.id=item?.id||'';m.querySelector('[name="title"]').value=item?.title||'';m.querySelector('[name="category"]').value=item?.category||'Romantic';m.querySelector('[name="file"]').value='';m.querySelector('[name="active"]').checked=item?.active!==false}
async function saveMusic(e){e.preventDefault();const f=e.currentTarget,id=f.dataset.id,title=f.title.value.trim(),category=f.category.value,file=f.file.files[0],active=f.active.checked;if(!title)return mediaNotice('Data belum lengkap','Masukkan nama/judul musik.');if(!id&&!file)return mediaNotice('File MP3 belum dipilih','Pilih file MP3 terlebih dahulu.');try{let old=music.find(x=>x.id===id),url=old?.file_url||'',storagePath=old?.storage_path||'',oldPath=old?.storage_path||'';if(file){if(file.type!=='audio/mpeg'&&file.type!=='audio/mp3'&&!/\.mp3$/i.test(file.name))throw Error('File harus berformat MP3.');if(file.size>15*1024*1024)throw Error('Ukuran MP3 maksimal 15 MB.');storagePath=`music/${Date.now()}-${Math.random().toString(36).slice(2,8)}.mp3`;url=await uploadAdminFile(file,storagePath)}const payload={title,category,file_url:url,storage_path:storagePath,active,updated_at:new Date().toISOString()};if(id){const {error}=await supabaseClient.from('music_library').update(payload).eq('id',id);if(error)throw error}else{const {error}=await supabaseClient.from('music_library').insert(payload);if(error)throw error}if(file&&oldPath&&oldPath!==storagePath)await supabaseClient.storage.from('bernaung-media').remove([oldPath]);closeMediaModal();await loadMusic();mediaNotice('MP3 tersimpan','Musik berhasil diperbarui di koleksi Admin.')}catch(x){mediaNotice('Gagal menyimpan MP3',x.message||'Terjadi kesalahan.',true)}}
function deleteMusic(id){const item=music.find(x=>x.id===id);if(!item)return;mediaConfirm('Hapus MP3 ini?','Musik akan dihapus dari koleksi Admin.',async()=>{try{const {error}=await supabaseClient.from('music_library').delete().eq('id',id);if(error)throw error;if(item.storage_path)await supabaseClient.storage.from('bernaung-media').remove([item.storage_path]);await loadMusic();mediaNotice('MP3 dihapus','Musik sudah dihapus dari koleksi.')}catch(x){mediaNotice('Gagal menghapus MP3',x.message||'Terjadi kesalahan.',true)}})}
function closeMediaModal(){document.getElementById('adminMediaModal')?.classList.add('hidden')}
function setById(id){return defaultSets.find(x=>String(x.id)===String(id))||defaultSets[0]||null}
function filledCount(set){return (set?.items||[]).filter(x=>x.imageUrl).length}
function renderDefaults(){const box=document.getElementById('defaultPhotoManager');if(!box)return;if(!defaultSets.length){box.innerHTML='<div class="media-empty"><div class="media-empty-icon">▧</div><strong>Belum ada paket default</strong><p>Buat paket foto default untuk menyediakan pilihan gambar bagi customer.</p><button type="button" class="text-btn media-empty-action" data-open-default-manager>Kelola Default</button></div>';return}box.innerHTML=defaultSets.map(s=>{const thumbs=(s.items||[]).slice(0,8).map((x,i)=>x.imageUrl?`<img src="${esc(x.imageUrl)}" alt="Foto ${i+1}">`:`<span class="default-thumb-empty">${i+1}</span>`).join('');return `<article class="default-set-summary"><div class="default-set-main"><div class="default-set-top"><span class="eyebrow">${esc(s.name)}</span><b>${filledCount(s)}/8 foto</b></div><div class="default-thumb-strip">${thumbs}</div><small>${s.active?'Aktif untuk customer':'Nonaktif'}</small></div><button type="button" class="small-btn" data-manage-default="${esc(s.id)}">Kelola Foto</button></article>`}).join('')}
async function loadDefaults(){if(!supabaseReady())return;const {data,error}=await supabaseClient.rpc('get_default_photo_manager');if(error){mediaNotice('Gagal memuat foto default',error.message,true);return}defaultSets=data||[];renderDefaults();if(!activeDefaultId&&defaultSets[0])activeDefaultId=defaultSets[0].id}
function itemAt(set,index){return (set?.items||[]).find(x=>Number(x.slotIndex)===index)||{slotIndex:index,imageUrl:'',storagePath:''}}
function renderDefaultModal(){const modal=document.getElementById('adminDefaultModal');if(!modal)return;const set=setById(activeDefaultId);const tabs=defaultSets.map(s=>`<button type="button" class="default-tab ${String(s.id)===String(set?.id)?'active':''}" data-default-tab="${esc(s.id)}">${esc(s.name)}</button>`).join('');modal.querySelector('#defaultTabs').innerHTML=tabs+`<button type="button" class="default-tab add" data-add-default>+ TAMBAH DEFAULT</button>`;if(!set){modal.querySelector('#defaultPhotoEditor').innerHTML='<div class="empty-inline">Belum ada default.</div>';return}const labels=['Mempelai Pria','Mempelai Wanita','Foto Bersama 1','Foto Bersama 2','Foto Bersama 3','Foto Bersama 4','Foto Bersama 5','Foto Bersama 6'];modal.querySelector('#defaultPhotoEditor').innerHTML=`<div class="default-editor-head"><div><span class="eyebrow">PAKET DEFAULT</span><h3>${esc(set.name)}</h3><p>Isi 8 foto untuk paket ini. Foto Bersama yang dipilih menjadi Cover tetap masuk Galeri.</p></div><div class="default-set-actions">${!['default1','default2'].includes(set.setKey)?`<button type="button" class="text-btn" data-rename-default="${esc(set.id)}">Edit nama</button><button type="button" class="text-btn danger-text" data-delete-default-set="${esc(set.id)}">Hapus default</button>`:''}</div></div><div class="default-slot-grid">${labels.map((label,i)=>{const item=itemAt(set,i);return `<article class="default-slot"><div class="default-slot-preview">${item.imageUrl?`<img src="${esc(item.imageUrl)}" alt="${esc(label)}">`:'<span>Belum ada foto</span>'}</div><div class="default-slot-info"><b>${esc(label)}</b><label class="small-upload">${item.imageUrl?'Ganti foto':'Upload foto'}<input type="file" accept="image/jpeg,image/png,image/webp" data-default-slot="${i}"></label>${item.imageUrl?`<button type="button" class="text-btn danger-text" data-remove-default-slot="${i}">Hapus</button>`:''}</div>${i>=2?`<label class="cover-choice"><input type="radio" name="defaultCover" value="${i}" ${Number(set.coverPhotoIndex)===i?'checked':''} ${item.imageUrl?'':'disabled'}> <span>Jadikan Cover</span></label>`:''}</article>`}).join('')}</div><div class="default-editor-foot"><span>${filledCount(set)}/8 foto terisi</span><button type="button" class="small-btn" data-save-default-cover>Simpan Cover</button></div>`}
function openDefaultModal(id){activeDefaultId=id||defaultSets[0]?.id||'';renderDefaultModal();document.getElementById('adminDefaultModal')?.classList.remove('hidden')}
function closeDefaultModal(){document.getElementById('adminDefaultModal')?.classList.add('hidden')}
async function uploadDefaultSlot(setId,index,file){if(!file)return;if(file.size>8*1024*1024)return mediaNotice('Foto terlalu besar','Maksimal 8 MB per foto.');const set=setById(setId),old=itemAt(set,index);try{const ext=(file.name.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'')||'jpg';const path=`defaults/${setId}/${index}-${Date.now()}.${ext}`;const url=await uploadAdminFile(file,path);const {error}=await supabaseClient.from('default_photo_items').update({image_url:url,storage_path:path,active:true,updated_at:new Date().toISOString()}).eq('set_id',setId).eq('slot_index',index);if(error)throw error;if(old.storagePath&&old.storagePath!==path)await supabaseClient.storage.from('bernaung-media').remove([old.storagePath]);await loadDefaults();activeDefaultId=setId;renderDefaultModal();mediaNotice('Foto tersimpan','Foto default berhasil diperbarui.')}catch(x){mediaNotice('Gagal menyimpan foto',x.message||'Terjadi kesalahan.',true)}}
async function removeDefaultSlot(setId,index){const set=setById(setId),old=itemAt(set,index);if(!old.imageUrl)return;mediaConfirm('Hapus foto ini?','Slot foto tetap tersedia untuk diisi kembali.',async()=>{try{const {error}=await supabaseClient.from('default_photo_items').update({image_url:null,storage_path:null,active:true,updated_at:new Date().toISOString()}).eq('set_id',setId).eq('slot_index',index);if(error)throw error;if(old.storagePath)await supabaseClient.storage.from('bernaung-media').remove([old.storagePath]);if(Number(set.coverPhotoIndex)===index){await supabaseClient.from('default_photo_sets').update({cover_photo_index:2,updated_at:new Date().toISOString()}).eq('id',setId)}await loadDefaults();activeDefaultId=setId;renderDefaultModal();mediaNotice('Foto dihapus','Slot tetap tersedia untuk upload berikutnya.')}catch(x){mediaNotice('Gagal menghapus foto',x.message||'Terjadi kesalahan.',true)}})}
async function saveDefaultCover(setId){const choice=document.querySelector('input[name="defaultCover"]:checked');const index=Number(choice?.value??2);try{const {error}=await supabaseClient.from('default_photo_sets').update({cover_photo_index:index,updated_at:new Date().toISOString()}).eq('id',setId);if(error)throw error;await loadDefaults();activeDefaultId=setId;renderDefaultModal();mediaNotice('Cover tersimpan','Foto Cover untuk paket default sudah diperbarui.')}catch(x){mediaNotice('Gagal menyimpan Cover',x.message||'Terjadi kesalahan.',true)}}
async function addDefault(){const name=prompt('Nama default baru, contoh: DEFAULT ELEGANT');if(!name?.trim())return;try{const {data:set,error}=await supabaseClient.from('default_photo_sets').insert({name:name.trim(),active:true,cover_photo_index:2}).select('*').single();if(error)throw error;const rows=Array.from({length:8},(_,i)=>({set_id:set.id,slot_index:i}));const {error:itemError}=await supabaseClient.from('default_photo_items').insert(rows);if(itemError)throw itemError;await loadDefaults();activeDefaultId=set.id;renderDefaultModal();mediaNotice('Default ditambahkan','Paket default baru siap diisi 8 foto.')}catch(x){mediaNotice('Gagal menambah default',x.message||'Terjadi kesalahan.',true)}}
async function renameDefault(id){const set=setById(id);if(!set)return;const name=prompt('Nama default baru',set.name);if(!name?.trim()||name.trim()===set.name)return;try{const {error}=await supabaseClient.from('default_photo_sets').update({name:name.trim(),updated_at:new Date().toISOString()}).eq('id',id);if(error)throw error;await loadDefaults();activeDefaultId=id;renderDefaultModal();mediaNotice('Nama diperbarui','Nama paket default berhasil diubah.')}catch(x){mediaNotice('Gagal mengubah nama',x.message||'Terjadi kesalahan.',true)}}
async function deleteDefaultSet(id){const set=setById(id);if(!set||['default1','default2'].includes(set.setKey))return;mediaConfirm('Hapus default ini?','Paket dan seluruh 8 slot fotonya akan dihapus.',async()=>{try{const paths=(set.items||[]).map(x=>x.storagePath).filter(Boolean);const {error}=await supabaseClient.from('default_photo_sets').delete().eq('id',id);if(error)throw error;if(paths.length)await supabaseClient.storage.from('bernaung-media').remove(paths);await loadDefaults();activeDefaultId=defaultSets[0]?.id||'';renderDefaultModal();mediaNotice('Default dihapus','Paket default sudah dihapus.')}catch(x){mediaNotice('Gagal menghapus default',x.message||'Terjadi kesalahan.',true)}})}
// MP3 modal
const modal=document.createElement('div');modal.id='adminMediaModal';modal.className='admin-media-modal hidden';modal.innerHTML='<div class="admin-media-box"><button type="button" class="admin-modal-close" data-close-media-modal>×</button><span class="eyebrow">MP3 MANAGER</span><h2 id="mediaMusicTitle">Tambah MP3</h2><form id="mediaMusicForm"><label>Nama / Judul<input name="title" required placeholder="Contoh: A Thousand Years"></label><label>Kategori<select name="category">'+categories.map(c=>`<option>${c}</option>`).join('')+'</select></label><label>File MP3<input name="file" type="file" accept="audio/mpeg,.mp3"></label><label class="check-line"><input name="active" type="checkbox" checked> Aktif dan tersedia untuk customer</label><button class="btn btn-dark full-btn" type="submit">Simpan MP3</button></form></div>';document.body.appendChild(modal);
// Default modal
const dmodal=document.createElement('div');dmodal.id='adminDefaultModal';dmodal.className='admin-media-modal hidden';dmodal.innerHTML='<div class="admin-default-box"><button type="button" class="admin-modal-close" data-close-default-modal>×</button><div id="defaultTabs" class="default-tabs"></div><div id="defaultPhotoEditor"></div></div>';document.body.appendChild(dmodal);
document.getElementById('mediaMusicForm').addEventListener('submit',saveMusic);document.querySelector('[data-close-media-modal]').addEventListener('click',closeMediaModal);document.getElementById('adminMediaModal').addEventListener('click',e=>{if(e.target.id==='adminMediaModal')closeMediaModal()});
document.querySelector('[data-close-default-modal]').addEventListener('click',closeDefaultModal);document.getElementById('defaultPhotoEditor').addEventListener('change',e=>{const up=e.target.closest('[data-default-slot]');if(up?.files?.[0])uploadDefaultSlot(activeDefaultId,Number(up.dataset.defaultSlot),up.files[0])});document.getElementById('adminDefaultModal').addEventListener('click',async e=>{if(e.target.id==='adminDefaultModal')return closeDefaultModal();const tab=e.target.closest('[data-default-tab]');if(tab){activeDefaultId=tab.dataset.defaultTab;renderDefaultModal();return}if(e.target.closest('[data-add-default]'))return addDefault();const up=e.target.closest('[data-default-slot]');if(up?.files?.[0])return uploadDefaultSlot(activeDefaultId,Number(up.dataset.defaultSlot),up.files[0]);const rm=e.target.closest('[data-remove-default-slot]');if(rm)return removeDefaultSlot(activeDefaultId,Number(rm.dataset.removeDefaultSlot));if(e.target.closest('[data-save-default-cover]'))return saveDefaultCover(activeDefaultId);const rn=e.target.closest('[data-rename-default]');if(rn)return renameDefault(rn.dataset.renameDefault);const del=e.target.closest('[data-delete-default-set]');if(del)return deleteDefaultSet(del.dataset.deleteDefaultSet)});
document.getElementById('addMusicBtn')?.addEventListener('click',()=>musicModal());document.getElementById('musicManagerList')?.addEventListener('click',e=>{if(e.target.closest('[data-add-empty-music]'))musicModal()});document.getElementById('defaultPhotoManager')?.addEventListener('click',e=>{if(e.target.closest('[data-open-default-manager]'))openDefaultModal(defaultSets[0]?.id)});document.getElementById('musicManagerList')?.addEventListener('click',e=>{const ed=e.target.closest('[data-edit-music]');if(ed)musicModal(music.find(x=>x.id===ed.dataset.editMusic));const del=e.target.closest('[data-delete-music]');if(del)deleteMusic(del.dataset.deleteMusic)});document.getElementById('defaultPhotoManager')?.addEventListener('click',e=>{const b=e.target.closest('[data-manage-default]');if(b)openDefaultModal(b.dataset.manageDefault)});document.getElementById('openDefaultManagerBtn')?.addEventListener('click',()=>openDefaultModal(defaultSets[0]?.id));
(async()=>{if(!supabaseReady())return;await loadMusic();await loadDefaults()})();
})();
