(function(){
const login=document.getElementById('manageLogin'),panel=document.getElementById('managePanel'),err=document.getElementById('manageError');
if(!login||!panel)return;
const params=new URLSearchParams(location.search);
const manageId=params.get('id')||location.pathname.split('/').filter(Boolean).pop()||'';
let accessCode='',data=null,overview=null,musicLibrary=[];
const templates=[
{id:3,name:'Adat Nusantara',cat:'Elegant',url:'/templates/adat-nusantara.html'},
{id:13,name:'Playful Ceria',cat:'Playful',url:'/templates/playful-ceria.html'}
];
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const val=v=>String(v??'').trim();
const photoUrls=d=>Array.isArray(d)?d.map(x=>typeof x==='string'?x:(x?.url||'')).map(val):[];
const money=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n||0));
function abs(u){if(!u)return'';return /^https?:\/\//i.test(u)?u:location.origin+'/'+String(u).replace(/^\//,'')}
function notice(t,c=''){const n=document.getElementById('manageNotice');if(n){n.textContent=t;n.className='manage-notice '+c}}
function openSavedModal(){document.getElementById('saveSuccessModal')?.classList.remove('hidden')}
function closeSavedModal(){document.getElementById('saveSuccessModal')?.classList.add('hidden')}
function openConfirm(title,message,callback){const m=document.getElementById('manageConfirmModal');if(!m)return;document.getElementById('confirmTitle').textContent=title;document.getElementById('confirmMessage').textContent=message;m.classList.remove('hidden');m._callback=callback}
function closeConfirm(){const m=document.getElementById('manageConfirmModal');if(m)m.classList.add('hidden')}
function scheduleRow(a,i){return `<div class="data-row"><div class="row-fields"><input data-st="title" data-i="${i}" value="${esc(a.title||'')}" placeholder="Nama acara"><input data-st="time" data-i="${i}" value="${esc(a.time||'')}" placeholder="08.00 WIB"></div><button type="button" class="icon-btn danger" data-rs="${i}">Hapus</button></div>`}
function accountCard(a,i){const n=val(a.number),masked=n?('•••• •••• '+n.slice(-4)):'Nomor rekening belum diisi';return `<article class="account-card"><div><span class="mini-label">${esc(a.provider||'REKENING')}</span><strong>${esc(masked)}</strong><small>${esc(a.name||'Nama pemilik belum diisi')}</small></div><div class="row-actions"><button type="button" class="text-btn" data-edit-account="${i}">Edit</button><button type="button" class="text-btn danger-text" data-delete-account="${i}">Hapus</button></div></article>`}
function photoSlot(url,index,label,coverIndex,mode){const checked=Number(coverIndex)===index&&mode==='own';return `<article class="photo-card" data-photo-card="${index}"><div class="photo-preview ${url?'has-photo':''}">${url?`<img src="${esc(url)}" alt="${esc(label)}">`:'<span>Belum ada foto</span>'}</div><div class="photo-card-info"><div><b>${esc(label)}</b><small>${url?'Foto tersimpan':'Belum diisi'}</small></div><div class="row-actions"><label class="upload-btn">${url?'Ganti foto':'Upload foto'}<input class="photo-file" data-photo="${index}" type="file" accept="image/jpeg,image/png,image/webp"></label>${url?`<button type="button" class="text-btn danger-text" data-remove-photo="${index}">Hapus</button>`:''}</div></div>${index>=2?`<label class="cover-choice"><input type="radio" name="coverPhoto" value="${index}" ${checked?'checked':''} ${mode!=='own'?'disabled':''}> <span>Jadikan foto cover</span></label>`:''}</article>`}
function musicChoices(){
 const selected=val(data.music);
 const rows=musicLibrary.map(m=>`<label class="music-choice"><input type="radio" name="musicChoice" value="${esc(m.file_url)}" ${selected===m.file_url?'checked':''}><span><b>${esc(m.title)}</b><small>${esc(m.category)}</small></span><button type="button" class="music-preview" data-preview-music="${esc(m.file_url)}">▶</button></label>`).join('');
 return `${rows}<label class="music-choice"><input type="radio" name="musicChoice" value="" ${!selected?'checked':''}><span><b>Tanpa Musik</b><small>Undangan tidak memakai musik latar</small></span></label>${rows?'':'<div class="empty-inline">Belum ada musik tersedia dari Admin MP3 Manager.</div>'}`;
}
function render(d){
 const ls=Array.isArray(d.loveStory)?d.loveStory:[],ss=Array.isArray(d.schedules)?d.schedules:[],ac=Array.isArray(d.accounts)?d.accounts:[],photos=photoUrls(d.photos||[]),defaultSets=Array.isArray(d.defaultPhotos)?d.defaultPhotos:[],activeTemplate=templates.find(t=>String(t.id)===String(d.templateId))||templates[0],changeCount=Number(d.templateChangeCount||0),photoMode=d.photoMode||'own';
 panel.innerHTML=`
 <div class="manage-workspace-head"><div><span class="eyebrow">BERNAUNG · MANAGE</span><h2>${esc(d.groom||'Mempelai')} <i>&</i> ${esc(d.bride||'')}</h2><p>Kelola, pantau, dan bagikan undangan dari satu ruang.</p></div><div class="manage-head-actions"><a class="btn btn-light btn-sm" href="${esc(abs(d.inviteUrl||('/'+d.invite_slug)))}" target="_blank" rel="noopener">Preview</a><button class="btn btn-dark btn-sm" id="saveTop" type="button">Simpan</button></div></div>
 <div class="manage-tabs" role="tablist"><button type="button" class="manage-tab active" data-main-tab="overview">Overview</button><button type="button" class="manage-tab" data-main-tab="edit">Edit Undangan</button><button type="button" class="manage-tab" data-main-tab="guest-links">Link Tamu</button><button type="button" class="manage-tab" data-main-tab="access">Akses</button></div>
 <div class="manage-notice" id="manageNotice">Perubahan disimpan setelah menekan Simpan.</div>
 <div class="manage-tab-panel active" data-tab-panel="overview"><div id="manageOverview" class="manage-overview"></div></div>
 <div class="manage-tab-panel" data-tab-panel="edit"><form id="manageEditor" class="manage-editor">
  <section class="manage-section"><div class="section-head"><div><span class="eyebrow">01</span><h3>Mempelai</h3></div><p>Data yang tampil di seluruh undangan.</p></div><div class="form-grid"><label>Nama lengkap pria<input name="groom" value="${esc(d.groom)}" required></label><label>Nama lengkap wanita<input name="bride" value="${esc(d.bride)}" required></label><label>Nama panggilan pria<input name="groomNickname" value="${esc(d.groomNickname)}"></label><label>Nama panggilan wanita<input name="brideNickname" value="${esc(d.brideNickname)}"></label><label>Instagram pria <span class="optional">opsional</span><input name="groomInstagram" value="${esc(d.groomInstagram)}" placeholder="@username"></label><label>Instagram wanita <span class="optional">opsional</span><input name="brideInstagram" value="${esc(d.brideInstagram)}" placeholder="@username"></label></div></section>
  <section class="manage-section"><div class="section-head"><div><span class="eyebrow">02</span><h3>Orang Tua</h3></div><p>Nama orang tua kedua mempelai.</p></div><div class="form-grid"><label>Ayah mempelai pria<input name="groomFather" value="${esc(d.groomFather)}"></label><label>Ibu mempelai pria<input name="groomMother" value="${esc(d.groomMother)}"></label><label>Ayah mempelai wanita<input name="brideFather" value="${esc(d.brideFather)}"></label><label>Ibu mempelai wanita<input name="brideMother" value="${esc(d.brideMother)}"></label></div></section>
  <section class="manage-section"><div class="section-head"><div><span class="eyebrow">03</span><h3>Acara</h3></div><p>Detail waktu dan lokasi acara.</p></div><div class="form-grid"><label>Jenis acara<select name="eventType"><option value="Akad & Resepsi" ${d.eventType==='Akad & Resepsi'?'selected':''}>Akad &amp; Resepsi</option><option value="Akad" ${d.eventType==='Akad'?'selected':''}>Akad</option><option value="Resepsi" ${d.eventType==='Resepsi'?'selected':''}>Resepsi</option></select></label><label>Tanggal<input type="date" name="date" value="${esc(d.date)}" required></label><label>Waktu<input name="time" value="${esc(d.time)}" required></label><label>Nama tempat<input name="venue" value="${esc(d.venue)}"></label><label class="full">Alamat lengkap<input name="address" value="${esc(d.address)}"></label><label class="full">Google Maps URL<input name="maps" value="${esc(d.maps)}" required></label></div></section>
  <section class="manage-section"><div class="section-head"><div><span class="eyebrow">04</span><h3>Love Story</h3></div><p>Dua cerita opsional. Foto pendukung diambil dari 6 Foto Bersama.</p></div><div class="story-grid">${[0,1].map(i=>`<div class="story-card"><span>Cerita ${i+1}</span><input data-ls="title" data-i="${i}" value="${esc(ls[i]?.title||'')}" placeholder="Judul singkat"><textarea data-ls="text" data-i="${i}" rows="5" placeholder="Tulis cerita...">${esc(ls[i]?.text||'')}</textarea></div>`).join('')}</div><p class="helper">Jika kosong, template menggunakan teks netral bawaan.</p></section>
  <section class="manage-section"><div class="section-head"><div><span class="eyebrow">05</span><h3>Susunan Acara</h3></div><p>Tambahkan hanya acara yang ingin ditampilkan.</p></div><div id="scheduleList" class="stack-list">${ss.map(scheduleRow).join('')}</div><button type="button" class="outline-add" id="addSchedule">+ Tambah acara</button></section>
  <section class="manage-section"><div class="section-head"><div><span class="eyebrow">06</span><h3>Rekening / Gift</h3></div><p>Informasi hadiah digital.</p></div><div id="accountList" class="account-list">${ac.map(accountCard).join('')||'<div class="empty-inline">Belum ada rekening.</div>'}</div><button type="button" class="outline-add" id="addAccount">+ Tambah rekening</button></section>
  <section class="manage-section"><div class="section-head"><div><span class="eyebrow">07</span><h3>Foto</h3></div><p>Pilih memakai foto sendiri atau salah satu paket foto default Bernaung.</p></div><div class="photo-mode-grid"><label class="photo-mode-card"><input type="radio" name="photoMode" value="own" ${photoMode==='own'?'checked':''}><span><b>Gunakan foto saya</b><small>2 foto mempelai + 6 Foto Bersama</small></span></label>${defaultSets.map(set=>{const complete=(set.items||[]).filter(x=>x.imageUrl).length===8;return `<label class="photo-mode-card ${complete?'':'is-disabled'}"><input type="radio" name="photoMode" value="${esc(set.id)}" ${String(photoMode)===String(set.id)?'checked':''} ${complete?'':'disabled'}><span><b>${esc(set.name)}</b><small>${complete?'8 foto siap digunakan':'Belum tersedia · Admin belum melengkapi 8 foto'}</small></span></label>`}).join('')}</div>${photoMode==='own'?`<div class="photo-group"><div class="photo-group-head"><div><b>Mempelai pria</b><span>1 foto</span></div><small>Dipakai khusus profil pria.</small></div><div class="photo-single">${photoSlot(photos[0]||'',0,'Mempelai pria',d.coverPhotoIndex,photoMode)}</div></div><div class="photo-group"><div class="photo-group-head"><div><b>Mempelai wanita</b><span>1 foto</span></div><small>Dipakai khusus profil wanita.</small></div><div class="photo-single">${photoSlot(photos[1]||'',1,'Mempelai wanita',d.coverPhotoIndex,photoMode)}</div></div><div class="photo-group"><div class="photo-group-head"><div><b>Foto Bersama</b><span>6 foto</span></div><small>Semuanya tampil di Galeri. Salah satunya bisa jadi Cover.</small></div><div class="photo-grid">${Array.from({length:6},(_,i)=>photoSlot(photos[i+2]||'',i+2,`Foto Bersama ${i+1}`,d.coverPhotoIndex,photoMode)).join('')}</div></div><p class="helper">JPG, PNG, atau WebP. Maksimal 8 MB per foto. Foto Cover tetap tampil di Galeri.</p>`:`<div class="default-selected-note"><b>Paket foto default dipilih.</b><span>8 foto akan digunakan otomatis oleh template. Untuk mengganti fotonya, Admin perlu memperbarui paket default.</span></div>`}</section>
  <section class="manage-section"><div class="section-head"><div><span class="eyebrow">08</span><h3>Musik</h3></div><p>Pilih musik yang sudah tersedia dari Admin MP3 Manager.</p></div><div class="music-choice-list">${musicChoices()}</div></section>
  <section class="manage-section"><div class="section-head"><div><span class="eyebrow">09</span><h3>Kontak</h3></div><p>Nomor WhatsApp untuk tamu.</p></div><label>WhatsApp<input name="whatsapp" value="${esc(d.whatsapp)}" placeholder="08xxxxxxxxxx" required></label></section>
  <section class="manage-section"><div class="section-head"><div><span class="eyebrow">10</span><h3>Template</h3></div><p>Ganti tema maksimal 2 kali.</p></div><div class="template-limit"><strong>Penggantian tema: ${changeCount}/2</strong><span>${changeCount>=2?'Kesempatan penggantian tema sudah habis.':'Setiap memilih tema berbeda, satu kesempatan digunakan.'}</span></div><label>Tema<select name="templateId" id="manageTemplateSelect" ${changeCount>=2?'data-locked="true"':''}>${templates.map(t=>`<option value="${t.id}" ${String(d.templateId)===String(t.id)?'selected':''}>${esc(t.name)} — ${esc(t.cat)}</option>`).join('')}</select></label><div class="template-preview"><iframe id="templateFrame" src="${esc(activeTemplate.url)}" loading="lazy"></iframe><div><span class="mini-label">TEMA AKTIF</span><b id="templateName">${esc(activeTemplate.name)}</b><p id="templateCat">${esc(activeTemplate.cat)}</p></div></div></section>
  <section class="manage-section"><div class="section-head"><div><span class="eyebrow">11</span><h3>Catatan</h3></div><p>Tambahan yang ingin ditampilkan atau diingat.</p></div><textarea name="notes" rows="5" placeholder="Tulis catatan tambahan...">${esc(d.notes||'')}</textarea></section>
  <div class="save-bar"><button class="btn btn-dark full-btn" type="submit">Simpan perubahan</button></div>
 </form></div>
 <div class="manage-tab-panel" data-tab-panel="guest-links"><section class="manage-tool-card"><div class="section-head"><div><span class="eyebrow">LINK TAMU</span><h3>Generator link personal</h3></div><p>Maksimal 50 nama, satu nama per baris.</p></div><label>Nama tamu<textarea id="guestNames" rows="10" placeholder="Budi\nSiti\nAndi\nRina"></textarea></label><div class="guest-generator-actions"><button type="button" class="btn btn-dark" id="generateGuestLinks">Generate link</button><span id="guestCount" class="guest-count">0 nama</span></div><div id="guestLinksResult" class="guest-links-result"></div></section></div>
 <div class="manage-tab-panel" data-tab-panel="access"><section class="manage-tool-card access-page-card"><div class="section-head"><div><span class="eyebrow">AKSES</span><h3>Link & kode</h3></div><p>Simpan informasi ini di tempat yang aman.</p></div><div class="access-list"><div class="access-row"><div><span>Link Undangan</span><strong>${esc(abs(d.inviteUrl||('/'+d.invite_slug)))}</strong></div><div class="access-row-actions"><button type="button" class="text-btn" data-copy="${esc(abs(d.inviteUrl||('/'+d.invite_slug)))}">Salin</button><a class="text-btn" href="${esc(abs(d.inviteUrl||('/'+d.invite_slug)))}" target="_blank" rel="noopener">Buka</a></div></div><div class="access-row"><div><span>Link Manage</span><strong>${esc(abs(d.manageUrl||('/m/'+manageId)))}</strong></div><div class="access-row-actions"><button type="button" class="text-btn" data-copy="${esc(abs(d.manageUrl||('/m/'+manageId)))}">Salin</button><a class="text-btn" href="${esc(abs(d.manageUrl||('/m/'+manageId)))}" target="_blank" rel="noopener">Buka</a></div></div><div class="access-row"><div><span>Kode Rahasia</span><strong id="secretCodeValue">••••••••</strong></div><div class="access-row-actions"><button type="button" class="text-btn" id="toggleSecret">Tampilkan</button><button type="button" class="text-btn" data-copy="${esc(accessCode)}">Salin</button></div></div></div><a class="btn btn-dark full-btn" href="https://wa.me/?text=${encodeURIComponent('Undangan '+(d.groom||'')+' & '+(d.bride||'')+' — '+abs(d.inviteUrl||('/'+d.invite_slug)))}" target="_blank" rel="noopener">Bagikan via WhatsApp</a></section></div>
 <div id="accountModal" class="manage-modal hidden"><div class="manage-modal-box"><span class="eyebrow">REKENING</span><h2>Atur rekening</h2><form id="accountForm"><label>Bank / E-Wallet<input name="provider" placeholder="BCA / Mandiri / DANA"></label><label>Nomor rekening / tujuan<input name="number" placeholder="Nomor rekening / tujuan"></label><label>Atas nama<input name="name" placeholder="Nama pemilik rekening"></label><div class="modal-actions"><button type="button" class="btn btn-light" data-close-account>Batal</button><button type="submit" class="btn btn-dark">Simpan</button></div></form></div></div><div id="saveSuccessModal" class="manage-modal hidden" aria-hidden="true"><div class="manage-modal-box"><span class="eyebrow">TERSIMPAN</span><h2>Perubahan berhasil disimpan</h2><p>Semua perubahan pada undanganmu sudah tersimpan.</p><button type="button" class="btn btn-dark full-btn" data-close-success>Oke</button></div></div>
 <div id="manageConfirmModal" class="manage-modal hidden"><div class="manage-modal-box"><span class="eyebrow">KONFIRMASI</span><h2 id="confirmTitle">Konfirmasi</h2><p id="confirmMessage"></p><div class="modal-actions"><button type="button" class="btn btn-light" data-close-confirm>Batal</button><button type="button" class="btn btn-dark" id="confirmAction">Lanjutkan</button></div></div></div>`;
 bindEditor();loadOverview();
}
function setTab(name){document.querySelectorAll('[data-tab-panel]').forEach(x=>x.classList.toggle('active',x.dataset.tabPanel===name));document.querySelectorAll('[data-main-tab]').forEach(x=>x.classList.toggle('active',x.dataset.mainTab===name));if(name==='overview')loadOverview()}
async function loadMusic(){musicLibrary=[];if(!supabaseReady())return;try{const {data:r,error}=await supabaseClient.from('music_library').select('id,title,category,file_url,active').eq('active',true).order('category').order('title');if(!error)musicLibrary=r||[]}catch(e){console.error(e)}}
async function loadOverview(){const box=document.getElementById('manageOverview');if(!box||!data)return;box.innerHTML='<div class="overview-loading">Memuat ringkasan…</div>';try{let o=null;if(supabaseReady()){const {data:r,error}=await supabaseClient.rpc('get_manage_overview',{p_manage_id:manageId,p_secret_code:accessCode});if(!error)o=r}overview=o||{};const stats=overview.stats||{};const rsvps=overview.rsvps||[];const hadir=rsvps.filter(r=>r.attendance==='hadir'),tidak=rsvps.filter(r=>r.attendance==='tidak_hadir');box.innerHTML=`<div class="overview-grid"><div class="overview-stat"><span>Dibuka</span><strong>${Number(stats.totalOpens||0)}</strong></div><div class="overview-stat"><span>Pengunjung unik</span><strong>${Number(stats.uniqueVisitors||0)}</strong></div><div class="overview-stat"><span>Hadir</span><strong>${hadir.length}</strong></div><div class="overview-stat"><span>Tidak hadir</span><strong>${tidak.length}</strong></div></div><section class="overview-card"><div class="overview-card-head"><div><span class="eyebrow">RSVP</span><h3>Daftar konfirmasi</h3></div><span>${rsvps.length} respons</span></div>${rsvps.length?rsvps.map(r=>`<div class="overview-rsvp"><div><strong>${esc(r.guest_name)}</strong><small>${r.attendance==='hadir'?'Hadir':'Tidak hadir'} · ${Number(r.guest_count||1)} orang</small></div><div><span>${esc(r.message||'')}</span><small>${new Date(r.created_at).toLocaleString('id-ID')}</small></div></div>`).join(''):'<div class="empty-inline">Belum ada RSVP.</div>'}</section><section class="overview-card"><div class="overview-card-head"><div><span class="eyebrow">UNDANGAN</span><h3>Informasi aktif</h3></div><span>${esc(data.templateName||'-')}</span></div><div class="overview-detail-grid"><div><span>Mempelai</span><strong>${esc(data.groom||'-')} & ${esc(data.bride||'-')}</strong></div><div><span>Acara</span><strong>${esc(data.eventType||'-')} · ${esc(data.date||'-')}</strong></div><div><span>Tempat</span><strong>${esc(data.venue||'-')}</strong></div><div><span>Terakhir dibuka</span><strong>${stats.lastOpened?new Date(stats.lastOpened).toLocaleString('id-ID'):'Belum ada'}</strong></div></div></section>`}catch(x){console.error(x);box.innerHTML='<div class="empty-inline">Gagal memuat Overview.</div>'}}
function guestLinkItems(){const raw=String(document.getElementById('guestNames')?.value||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean).slice(0,50);const c=document.getElementById('guestCount');if(c)c.textContent=`${raw.length} nama`;return raw}
function generateGuestLinks(){const names=guestLinkItems(),base=abs(data.inviteUrl||('/'+data.invite_slug)),box=document.getElementById('guestLinksResult');if(!names.length){box.innerHTML='<div class="empty-inline">Masukkan nama tamu terlebih dahulu.</div>';return}box.innerHTML=`<div class="guest-result-actions"><button type="button" class="btn btn-light" id="copyAllGuests">Salin semua</button><button type="button" class="btn btn-light" id="exportGuests">Export TXT</button></div>`+names.map(n=>{const url=base+'?to='+encodeURIComponent(n);return `<div class="guest-link-row"><div><strong>${esc(n)}</strong><span>${esc(url)}</span></div><button type="button" class="text-btn" data-copy="${esc(url)}">Salin</button></div>`}).join('');document.getElementById('copyAllGuests').onclick=()=>navigator.clipboard.writeText(names.map(n=>base+'?to='+encodeURIComponent(n)).join('\n')).then(()=>notice('Semua link tamu disalin.','success')).catch(()=>notice('Gagal menyalin.','error'));document.getElementById('exportGuests').onclick=()=>{const blob=new Blob([names.map(n=>`${n}\n${base}?to=${encodeURIComponent(n)}`).join('\n\n')+'\n'],{type:'text/plain;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`link-tamu-${data.invite_slug||'undangan'}.txt`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}}
function collect(){const fd=new FormData(document.getElementById('manageEditor')),t=templates.find(x=>String(x.id)===String(fd.get('templateId')))||templates[0];return {groom:val(fd.get('groom')),bride:val(fd.get('bride')),groomNickname:val(fd.get('groomNickname')),brideNickname:val(fd.get('brideNickname')),groomInstagram:val(fd.get('groomInstagram')),brideInstagram:val(fd.get('brideInstagram')),groomFather:val(fd.get('groomFather')),groomMother:val(fd.get('groomMother')),brideFather:val(fd.get('brideFather')),brideMother:val(fd.get('brideMother')),eventType:val(fd.get('eventType')),date:val(fd.get('date')),time:val(fd.get('time')),venue:val(fd.get('venue')),address:val(fd.get('address')),maps:val(fd.get('maps')),whatsapp:val(fd.get('whatsapp')),music:[...document.querySelectorAll('input[name="musicChoice"]')].find(x=>x.checked)?.value||'',notes:val(fd.get('notes')),photos:photoUrls(data.photos||[]),loveStory:loveStory.filter(x=>x?.title||x?.text),schedules:schedules.filter(x=>x.title||x.time),accounts:accounts.filter(x=>x.provider||x.number||x.name),photoMode:document.querySelector('input[name="photoMode"]:checked')?.value||'own',coverPhotoIndex:Number(document.querySelector('input[name="coverPhoto"]:checked')?.value??data.coverPhotoIndex??-1),templateId:t.id,templateName:t.name,templateCategory:t.cat,templateUrl:t.url}}
let schedules=[],accounts=[],loveStory=[];
function bindEditor(){
 schedules=Array.isArray(data.schedules)?data.schedules.map(x=>({title:x.title||'',time:x.time||''})):[];accounts=Array.isArray(data.accounts)?data.accounts.map(x=>({provider:x.provider||'',number:x.number||'',name:x.name||''})):[];loveStory=Array.isArray(data.loveStory)?data.loveStory.map(x=>({title:x.title||'',text:x.text||''})):[];
 const editor=document.getElementById('manageEditor');editor.addEventListener('input',e=>{const i=Number(e.target.dataset.i);if(e.target.dataset.st)schedules[i][e.target.dataset.st]=e.target.value;if(e.target.dataset.ls)loveStory[i][e.target.dataset.ls]=e.target.value});
 document.getElementById('addSchedule').onclick=()=>{schedules.push({title:'',time:''});rerenderSchedules()};document.getElementById('addAccount').onclick=()=>openAccount();
 document.querySelectorAll('[data-main-tab]').forEach(b=>b.onclick=()=>setTab(b.dataset.mainTab));document.getElementById('generateGuestLinks').onclick=generateGuestLinks;document.getElementById('guestNames').addEventListener('input',guestLinkItems);
 document.getElementById('toggleSecret').onclick=e=>{const s=document.getElementById('secretCodeValue'),shown=s.textContent===accessCode;s.textContent=shown?'••••••••':accessCode;e.currentTarget.textContent=shown?'Tampilkan':'Sembunyikan'};
 editor.addEventListener('submit',save);document.getElementById('saveTop').onclick=save;
 editor.addEventListener('change',e=>{if(e.target.name==='photoMode'){const mode=e.target.value;document.querySelectorAll('input[name="coverPhoto"]').forEach(x=>x.disabled=mode!=='own')}});
 document.querySelectorAll('[data-preview-music]').forEach(b=>b.onclick=()=>previewMusic(b.dataset.previewMusic));
 panel.addEventListener('click',async e=>{const cp=e.target.closest('[data-copy]');if(cp){try{await navigator.clipboard.writeText(cp.dataset.copy||'');notice('Disalin.','success')}catch(_){notice('Gagal menyalin.','error')}}const rm=e.target.closest('[data-remove-photo]');if(rm){const i=Number(rm.dataset.removePhoto);openConfirm('Hapus foto ini?','Foto akan dihapus dari undangan.',async()=>{const next=photoUrls(data.photos||[]);next[i]='';while(next.length&&!next[next.length-1])next.pop();try{await persistPhotos(next);data.photos=next;if(Number(data.coverPhotoIndex)===i)data.coverPhotoIndex=-1;render(data);setTab('edit');notice('Foto dihapus.','success')}catch(x){notice(x.message||'Gagal menghapus foto.','error')}})}if(e.target.closest('[data-edit-account]'))openAccount(Number(e.target.closest('[data-edit-account]').dataset.editAccount));if(e.target.closest('[data-delete-account]')){const i=Number(e.target.closest('[data-delete-account]').dataset.deleteAccount);openConfirm('Hapus rekening ini?','Data rekening ini akan dihapus dari undangan.',()=>{accounts.splice(i,1);rerenderAccounts()})}if(e.target.closest('[data-close-success]'))closeSavedModal();if(e.target.closest('[data-close-confirm]'))closeConfirm();if(e.target.closest('[data-close-account]'))closeAccount()});
 document.getElementById('confirmAction').onclick=async()=>{const cb=document.getElementById('manageConfirmModal')._callback;closeConfirm();if(cb)await cb()};
 document.getElementById('accountForm').addEventListener('submit',e=>{e.preventDefault();const f=e.currentTarget,i=f.closest('#accountModal').dataset.index,item={provider:val(f.provider.value),number:val(f.number.value),name:val(f.name.value)};if(i==='')accounts.push(item);else accounts[Number(i)]=item;rerenderAccounts();closeAccount()});
 document.getElementById('manageTemplateSelect').addEventListener('change',e=>{const current=String(data.templateId||'');if(Number(data.templateChangeCount||0)>=2&&e.target.value!==current){e.target.value=current;notice('Kesempatan penggantian tema sudah habis.','error');return}const t=templates.find(x=>String(x.id)===String(e.target.value))||templates[0];document.getElementById('templateFrame').src=t.url;document.getElementById('templateName').textContent=t.name;document.getElementById('templateCat').textContent=t.cat});
 panel.addEventListener('change',e=>{const input=e.target.closest('.photo-file');if(input?.files?.[0])uploadPhoto(Number(input.dataset.photo),input.files[0]);});
}
function rerenderSchedules(){const box=document.getElementById('scheduleList');if(box)box.innerHTML=schedules.map(scheduleRow).join('')}
function rerenderAccounts(){const box=document.getElementById('accountList');if(box)box.innerHTML=accounts.map(accountCard).join('')||'<div class="empty-inline">Belum ada rekening.</div>'}
function openAccount(index=null){const a=index===null?{provider:'',number:'',name:''}:accounts[index];const m=document.getElementById('accountModal');if(!m)return;m.classList.remove('hidden');m.dataset.index=index===null?'':index;m.querySelector('[name="provider"]').value=a.provider||'';m.querySelector('[name="number"]').value=a.number||'';m.querySelector('[name="name"]').value=a.name||''}
function closeAccount(){document.getElementById('accountModal')?.classList.add('hidden')}
async function save(e){e?.preventDefault();const next=collect();if(!next.groom||!next.bride||!next.date||!next.maps||!next.whatsapp){notice('Nama, tanggal, Google Maps, dan WhatsApp wajib diisi.','error');return}const oldTemplate=String(data.templateId||'');if(Number(data.templateChangeCount||0)>=2&&String(next.templateId)!==oldTemplate){notice('Kesempatan penggantian tema sudah habis.','error');return}const buttons=[document.getElementById('saveTop'),document.querySelector('.save-bar button')].filter(Boolean);buttons.forEach(b=>{b.disabled=true;b.dataset.originalText=b.textContent;b.textContent='Menyimpan…'});try{if(!supabaseReady()){data={...data,...next};notice('Perubahan berhasil disimpan.','success');openSavedModal();return}const {data:r,error}=await supabaseClient.rpc('update_manage_invitation',{p_manage_id:manageId,p_secret_code:accessCode,p_data:next});if(error)throw error;data={...data,...next,inviteUrl:r?.inviteUrl||data.inviteUrl,manageUrl:r?.manageUrl||data.manageUrl,templateChangeCount:Number(r?.templateChangeCount??data.templateChangeCount??0)};notice('Perubahan berhasil disimpan.','success');openSavedModal();if(String(next.templateId)!==oldTemplate)render(data)}catch(x){console.error(x);notice(x.message||'Gagal menyimpan.','error')}finally{buttons.forEach(b=>{b.disabled=false;b.textContent=b.dataset.originalText||'Simpan'})}}
async function uploadPhoto(index,file){if(!file)return;if(file.size>8*1024*1024){notice('Ukuran foto maksimal 8 MB.','error');return}if(!supabaseReady()){notice('Upload foto membutuhkan Supabase aktif.','error');return}const ext=(file.name.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'')||'jpg',path=`${manageId}/${Date.now()}-${Math.random().toString(36).slice(2,9)}.${ext}`;notice('Mengunggah foto…');try{const {error}=await supabaseClient.storage.from('invitation-photos').upload(path,file,{cacheControl:'3600',upsert:false,contentType:file.type});if(error)throw error;const {data:pub}=supabaseClient.storage.from('invitation-photos').getPublicUrl(path),next=photoUrls(data.photos||[]);next[index]=pub.publicUrl;await persistPhotos(next);data.photos=next;render(data);setTab('edit');notice('Foto berhasil diunggah.','success')}catch(x){console.error(x);notice(x.message||'Gagal mengunggah foto.','error')}}
async function persistPhotos(next){const {error}=await supabaseClient.rpc('update_manage_invitation',{p_manage_id:manageId,p_secret_code:accessCode,p_data:{photos:next}});if(error)throw error}
function previewMusic(url){if(!url)return;let a=document.getElementById('manageMusicPreview');if(!a){a=document.createElement('audio');a.id='manageMusicPreview';document.body.appendChild(a)}if(a.src===abs(url)&&!a.paused){a.pause();return}a.src=abs(url);a.play().catch(()=>{})}
login.addEventListener('submit',async e=>{e.preventDefault();accessCode=val(new FormData(login).get('code')).toUpperCase();err.textContent='';err.classList.remove('show');try{if(!manageId)throw Error('Link Manage tidak valid.');if(!supabaseReady()){data=getData();if(accessCode!==String(data.secretCode||data.secret||'').toUpperCase())throw Error('Kode rahasia tidak sesuai.')}else{const {data:r,error}=await supabaseClient.rpc('get_manage_invitation',{p_manage_id:manageId,p_secret_code:accessCode});if(error)throw error;if(!r)throw Error('Kode rahasia tidak sesuai atau undangan tidak aktif.');data=r;await loadMusic()}login.classList.add('hidden');panel.classList.remove('hidden');render(data)}catch(x){err.textContent=x.message||'Kode rahasia tidak sesuai.';err.classList.add('show')}});
})();
